"""Prior-period historical rates: the arithmetic, on data small enough to check by hand.

These are the features that read the outcome column, so they get the most
specific tests in the suite. The numbers below are worked out in the comments
rather than captured from a run — a golden-value test that was generated by the
code it tests will happily lock in a bug.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from src.features.historical import add_prior_period_rates, prior_period_rate


def _frame(rows: list[tuple[str, str, int]]) -> pd.DataFrame:
    """rows of (date, entity, denied)."""
    return pd.DataFrame(
        {
            "sim_submission_date": pd.to_datetime([r[0] for r in rows]),
            "entity": [r[1] for r in rows],
            "sim_denial_flag": [r[2] for r in rows],
        }
    )


def test_window_is_strictly_prior_and_embargoed() -> None:
    # With a 60-day embargo, the claim submitted on 2024-03-01 may look back no
    # further forward than 2024-01-01. Two prior claims for entity A, one denied.
    frame = _frame(
        [
            ("2024-01-01", "A", 1),
            ("2024-01-01", "A", 0),
            ("2024-03-01", "A", 1),
            ("2024-06-01", "A", 0),
        ]
    )
    result = prior_period_rate(
        frame,
        date_column="sim_submission_date",
        outcome_column="sim_denial_flag",
        key="entity",
        embargo_days=60,
        smoothing=0.0,
    )
    # The two January claims have nothing before them: no history, not zero.
    assert result.count.tolist() == [0.0, 0.0, 2.0, 3.0]
    assert np.isnan(result.raw_rate.iloc[0])
    assert result.raw_rate.iloc[2] == pytest.approx(0.5)
    # 2024-06-01 cuts off at 2024-04-02, so it sees all three earlier claims.
    assert result.raw_rate.iloc[3] == pytest.approx(2 / 3)


def test_a_claim_never_sees_itself() -> None:
    frame = _frame([("2024-01-01", "A", 1)])
    result = prior_period_rate(
        frame,
        date_column="sim_submission_date",
        outcome_column="sim_denial_flag",
        key="entity",
        embargo_days=1,
        smoothing=0.0,
    )
    assert result.count.iloc[0] == 0.0
    assert np.isnan(result.raw_rate.iloc[0])


def test_same_day_claims_are_invisible_to_each_other() -> None:
    """Nobody knows the outcome of a claim submitted the same morning."""
    frame = _frame([("2024-01-10", "A", 1), ("2024-01-10", "A", 0), ("2024-01-11", "A", 0)])
    result = prior_period_rate(
        frame,
        date_column="sim_submission_date",
        outcome_column="sim_denial_flag",
        key="entity",
        embargo_days=1,
        smoothing=0.0,
    )
    assert result.count.tolist() == [0.0, 0.0, 2.0]


def test_embargo_actually_holds_things_back() -> None:
    """The same data, two embargoes: the longer one must see strictly less."""
    frame = _frame([("2024-01-01", "A", 1), ("2024-02-01", "A", 0), ("2024-03-01", "A", 1)])
    kwargs = dict(
        date_column="sim_submission_date",
        outcome_column="sim_denial_flag",
        key="entity",
        smoothing=0.0,
    )
    short = prior_period_rate(frame, embargo_days=1, **kwargs)
    long = prior_period_rate(frame, embargo_days=60, **kwargs)
    assert short.count.tolist() == [0.0, 1.0, 2.0]
    assert long.count.tolist() == [0.0, 0.0, 1.0]


def test_zero_embargo_is_refused() -> None:
    """At zero the cutoff is the row's own date and the window includes itself."""
    frame = _frame([("2024-01-01", "A", 1)])
    with pytest.raises(ValueError, match="embargo_days"):
        prior_period_rate(
            frame,
            date_column="sim_submission_date",
            outcome_column="sim_denial_flag",
            key="entity",
            embargo_days=0,
        )


def test_entities_do_not_contaminate_each_other() -> None:
    frame = _frame(
        [
            ("2024-01-01", "A", 1),
            ("2024-01-01", "B", 0),
            ("2024-06-01", "A", 0),
            ("2024-06-01", "B", 0),
        ]
    )
    result = prior_period_rate(
        frame,
        date_column="sim_submission_date",
        outcome_column="sim_denial_flag",
        key="entity",
        embargo_days=60,
        smoothing=0.0,
    )
    assert result.raw_rate.iloc[2] == pytest.approx(1.0)  # A's own history only
    assert result.raw_rate.iloc[3] == pytest.approx(0.0)


def test_smoothing_pulls_a_thin_entity_to_the_book_rate() -> None:
    """One claim of history must not produce a 0.0 or 1.0 denial rate."""
    rows = [("2020-01-01", f"BULK{i % 4}", i % 5 == 0) for i in range(400)]
    rows.append(("2024-01-01", "THIN", 1))
    rows.append(("2024-06-01", "THIN", 0))
    frame = _frame([(d, e, int(v)) for d, e, v in rows])

    unsmoothed = prior_period_rate(
        frame,
        date_column="sim_submission_date",
        outcome_column="sim_denial_flag",
        key="entity",
        embargo_days=60,
        smoothing=0.0,
    )
    smoothed = prior_period_rate(
        frame,
        date_column="sim_submission_date",
        outcome_column="sim_denial_flag",
        key="entity",
        embargo_days=60,
        smoothing=20.0,
    )
    thin = frame.index[-1]
    assert unsmoothed.raw_rate.iloc[thin] == pytest.approx(1.0)  # 1 of 1, pure noise
    # Shrunk to (1 + 20 * book) / (1 + 20): nowhere near 1.0.
    assert smoothed.rate.iloc[thin] < 0.3
    assert smoothed.count.iloc[thin] == 1.0


def test_no_history_falls_back_to_the_book_rate_not_to_zero() -> None:
    """A brand-new provider is average until proven otherwise."""
    rows = [("2020-01-01", f"BULK{i % 4}", int(i % 5 == 0)) for i in range(400)]
    rows.append(("2024-01-01", "NEW", 0))
    frame = _frame(rows)
    result = prior_period_rate(
        frame,
        date_column="sim_submission_date",
        outcome_column="sim_denial_flag",
        key="entity",
        embargo_days=60,
        smoothing=20.0,
    )
    new = frame.index[-1]
    assert result.count.iloc[new] == 0.0
    assert result.rate.iloc[new] == pytest.approx(0.2, abs=0.02)  # the book rate


def test_the_earliest_claims_get_null_not_a_silent_zero() -> None:
    """Before any history exists the rate is unknown, and must say so.

    A zero here would tell the model the first claims in the warehouse came from
    flawless providers, which is a fabricated fact. NaN lets the imputer — fitted
    on the training fold — decide.
    """
    frame = _frame([("2024-01-01", "A", 1), ("2024-01-02", "B", 0)])
    result = prior_period_rate(
        frame,
        date_column="sim_submission_date",
        outcome_column="sim_denial_flag",
        key="entity",
        embargo_days=60,
        smoothing=20.0,
    )
    assert result.rate.isna().all()


def test_add_prior_period_rates_names_and_shapes() -> None:
    rows = [(f"2020-0{1 + i % 9}-01", f"P{i % 3}", int(i % 4 == 0)) for i in range(90)]
    frame = _frame(rows)
    frame["other"] = ["X", "Y"] * 45
    out = add_prior_period_rates(
        frame,
        date_column="sim_submission_date",
        outcome_column="sim_denial_flag",
        definitions={"sim_entity": "entity", "sim_other": "other"},
        embargo_days=30,
        smoothing=10.0,
    )
    for column in (
        "overall_prior_denial_rate",
        "sim_entity_prior_denial_rate",
        "sim_entity_prior_claims",
        "sim_other_prior_denial_rate",
        "sim_other_prior_claims",
    ):
        assert column in out.columns
    assert len(out) == len(frame)
    assert out.index.equals(frame.index)


def test_rates_are_bounded() -> None:
    rows = [(f"20{15 + i % 8}-06-01", f"P{i % 7}", int(i % 3 == 0)) for i in range(300)]
    out = add_prior_period_rates(
        _frame(rows),
        date_column="sim_submission_date",
        outcome_column="sim_denial_flag",
        definitions={"sim_entity": "entity"},
        embargo_days=60,
        smoothing=20.0,
    )
    rates = out["sim_entity_prior_denial_rate"].dropna()
    assert rates.between(0.0, 1.0).all()


def test_non_datetime_dates_are_refused() -> None:
    frame = _frame([("2024-01-01", "A", 1)])
    frame["sim_submission_date"] = frame["sim_submission_date"].astype(str)
    with pytest.raises(TypeError, match="datetime64"):
        prior_period_rate(
            frame,
            date_column="sim_submission_date",
            outcome_column="sim_denial_flag",
            key="entity",
        )
