"""Shared UI, and the one component CLAUDE.md §6 makes non-optional.

**Every page renders `render_synthetic_data_banner()`. No page ships without it.**
That is §6 verbatim, and §3.5 is why it is absolute rather than a nicety: Medicare
fee-for-service has exactly ONE payer and our payer dimension is 100% simulated,
so a payer comparison without the banner is a comparison of five payers that do
not exist. `tests/contracts/test_dashboard_banner.py` (qa's) fails the build for
any page module that renders content without calling it.

The banner is a component and not a copied paragraph for the same reason
`dashboard/disclosures.py` exists: five pages retyping a disclosure is five
chances for one of them to be softer than the others, and the soft one is the one
a reader will quote back.

EVERY FIGURE ON EVERY PAGE CARRIES ITS PROVENANCE
--------------------------------------------------
`kpi_row` takes a classification per metric — SOURCE, DERIVED, REFERENCE or
SIMULATED (§3.1) — and prints it under the number. A dashboard is the surface most
likely to launder a simulated dollar into a real one, because a big styled metric
tile reads as a fact about the world. The class under it is what stops that, and
it is a required argument rather than an optional one so a tile cannot ship
without a decision having been made about it.

`control_query` prints the SQL a figure must reconcile to, right beside the
figure. §7 requires dashboard totals to reconcile to SQL control queries; showing
the query where the number is means a reader can check it instead of trusting it.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

import altair as alt
import pandas as pd
import streamlit as st

from dashboard import disclosures
from dashboard.provenance import DashboardEmitter

Classification = Literal["SOURCE", "DERIVED", "REFERENCE", "SIMULATED", "MIXED"]

#: What each provenance class means in one line, shown on hover. Wording is the
#: §3.1 wording, not a paraphrase.
_CLASS_HELP: dict[str, str] = {
    "SOURCE": "From the official CMS synthetic claim files, unmodified.",
    "DERIVED": "Computed from SOURCE fields by this project's warehouse.",
    "REFERENCE": "From an official published code or facility reference file.",
    "SIMULATED": "Generated by THIS PROJECT'S simulation layer. Not a real outcome.",
    "MIXED": "Combines SOURCE, DERIVED and SIMULATED inputs — see the note below.",
}

_CLASS_BADGE: dict[str, str] = {
    "SOURCE": ":blue-badge[SOURCE]",
    "DERIVED": ":violet-badge[DERIVED]",
    "REFERENCE": ":green-badge[REFERENCE]",
    "SIMULATED": ":red-badge[SIMULATED]",
    "MIXED": ":orange-badge[MIXED]",
}


# ---------------------------------------------------------------------------
# The banner. CLAUDE.md §6.
# ---------------------------------------------------------------------------


def _banner_markdown() -> str:
    """The banner text, from the single source of truth in `disclosures.py`."""
    return disclosures.SYNTHETIC_DATA_BANNER


def render_synthetic_data_banner(extra: str | None = None, *, short: bool = False) -> None:
    """The §6 synthetic-data banner. Called at the top of every page.

    `extra` appends a page-specific note — the payer-dimension warning, the A/R
    shape note — INSIDE the same red block rather than beside it, so a reader
    cannot take the caveat and leave the banner behind.

    `short` renders the one-line form. §6 says no page ships without the banner,
    and that still holds: every page keeps a red block saying the outcomes are
    simulated. What changes is length, not coverage. Repeating six sentences at
    full width on all six pages trained the eye to skip the red block entirely,
    which is the opposite of what §6 is for — a disclosure nobody reads is not a
    disclosure. The full text stays one click away on Overview, in one place, so
    it is still findable in full rather than deleted.

    A page-specific `extra` is ALWAYS rendered in full, short form or not. Those
    are the warnings that apply to that page alone — the payer dimension, the
    work queue's membership selection — and they exist nowhere else, so
    shortening them would drop content rather than relocate it.
    """
    if short:
        body = disclosures.BANNER_SHORT_PAGE
        if extra:
            body = f"{body}\n\n{extra}"
        st.error(body, icon=":material/warning:")
        return
    body = _banner_markdown()
    if extra:
        body = f"{body}\n\n{extra}"
    st.error(body, icon=":material/warning:")


def summary_with_detail(
    summary: str,
    detail: str,
    *,
    label: str = "Full explanation",
    icon: str | None = None,
) -> None:
    """One plain sentence visible, the rigorous text one click below it.

    The dashboard's disclosures were written to be unarguable and they read like
    an audit transcript: hedged, interval-laden, several sentences before the
    point. A viewer scanning for a minute got none of it, because dense text at
    full length is skipped rather than read.

    NOTHING IS SHORTENED OR REMOVED HERE. `detail` is the existing text, moved
    from the page body into an expander directly beneath its own summary. Every
    figure, interval and caveat that was on the page is still on the page and
    still reachable without leaving it. What changes is that the reader gets the
    point first and chooses whether to read the proof.
    """
    st.markdown(summary)
    with st.expander(label, icon=icon):
        st.markdown(detail)


def render_page_header(title: str, subtitle: str, *, emitter: DashboardEmitter) -> None:
    """Title and one-line framing. **Does NOT render the banner, on purpose.**

    An earlier version of this function called the banner itself, and every page
    got it — correctly, invisibly, and by a chain a reader of the page file could
    not see. qa's `tests/contracts/test_dashboard_banner.py` reported all five
    pages as unbannered and it was right to: what it checks is that the CALL is
    in the page, and a §6 obligation discharged two frames away is one a future
    author can drop by editing this function.

    So the banner call stays in the page, on its own line, under §6's own words.
    """
    if not emitter.disclosure.strip():
        raise ValueError(f"{emitter.module}: dashboard emitter states no disclosure")
    st.title(title)
    st.caption(subtitle)


# ---------------------------------------------------------------------------
# KPI tiles with their provenance class attached
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Kpi:
    """One headline figure and the classification printed beneath it."""

    label: str
    value: str
    classification: Classification
    help: str = ""


#: Widest tile count that still shows a full money figure without CSS truncation.
#:
#: `st.metric` does not wrap. It ellipsises the value to whatever width its column
#: has, CLIENT-SIDE, so a value that fits in the DOM still reads as "$14…" on the
#: page. Four tiles in a row gave a quarter-width column, and
#: "$141,046,614.08" does not fit in a quarter of a laptop viewport — which is
#: why the Overview showed "20,…", "$14…", "12.…", "$6,…".
#:
#: Three is the widest that holds the longest value this dashboard renders. Rows
#: are chunked rather than shrunk so NO DIGIT IS DROPPED: abbreviating to
#: "$141.0M" would have fixed the layout by changing the number, and the figures
#: on this dashboard reconcile to SQL control queries exactly as printed.
_MAX_TILES_PER_ROW = 3


def kpi_row(kpis: list[Kpi], *, per_row: int = _MAX_TILES_PER_ROW) -> None:
    """Metric tiles stamped with provenance, chunked so values are not truncated.

    Renders in rows of at most `per_row`. A caller passing more than that gets
    several rows rather than one row of unreadably narrow tiles.
    """
    if per_row < 1:
        raise ValueError("per_row must be at least 1")
    for start in range(0, len(kpis), per_row):
        chunk = kpis[start : start + per_row]
        # Pad the final row so two leftover tiles keep the width of a full row's
        # tiles instead of stretching to half the page each.
        columns = st.columns(per_row)
        for column, kpi in zip(columns[: len(chunk)], chunk, strict=True):
            with column:
                st.metric(
                    kpi.label,
                    kpi.value,
                    help=(
                        f"{kpi.help}\n\n{kpi.classification}: {_CLASS_HELP[kpi.classification]}"
                    ).strip(),
                )
                st.markdown(_CLASS_BADGE[kpi.classification])


def provenance_note(classification: Classification, text: str) -> None:
    """A classified note under a table or chart."""
    st.caption(f"{_CLASS_BADGE[classification]} {text}")


# ---------------------------------------------------------------------------
# Reconciliation, shown where the figure is
# ---------------------------------------------------------------------------


#: Axis labels are never truncated. Vega-Lite's default `labelLimit` is 180px and
#: it ellipsises silently, which is how "MEDICAL_NECES…", "PRIOR_AUTH_MI…" and
#: "Medicaid Manage…" reached the screen. A denial category a reader cannot name
#: is not a denial category, and 0 means "no limit".
NO_LABEL_TRUNCATION = 0


def thin_volume_layer(
    frame: pd.DataFrame,
    *,
    month_column: str,
    count_column: str,
    ratio: float = 0.25,
) -> Any | None:
    """Shade the months whose claim count is too thin to read as a trend.

    Both time-series charts on this dashboard swing hard at the ends, and both
    already carry a caption saying why: those months are genuinely thin in the CMS
    extract. A caption below the chart is read AFTER the spike has already landed,
    so the annotation goes ON the chart — the caption stays exactly as it was.

    THIS ANNOTATES, IT DOES NOT FILTER. Every point still plots at its real value;
    a shaded band behind the line marks where the denominator is small. Dropping
    or smoothing the thin months would change the figures, which is the one thing
    this must not do.

    "Thin" is derived from the data rather than hard-coded to a date range, so it
    keeps meaning if the extract changes: a month is thin when its claim count is
    under `ratio` of the median month. Returns None when nothing qualifies, so a
    dense series gets no annotation rather than an empty band.
    """
    if frame.empty or count_column not in frame or month_column not in frame:
        return None
    counts = pd.to_numeric(frame[count_column], errors="coerce")
    median = counts.median()
    if not median or pd.isna(median):
        return None
    thin = frame.loc[counts < median * ratio, month_column].dropna().sort_values()
    if thin.empty:
        return None

    # Contiguous runs become one band each, so a leading and a trailing thin
    # stretch are two shaded regions rather than a stripe per month.
    months = list(pd.to_datetime(thin))
    bands: list[dict[str, Any]] = []
    start = previous = months[0]
    for current in months[1:]:
        if (current - previous).days > 62:  # a gap wider than one month ends the run
            bands.append({"start": start, "end": previous})
            start = current
        previous = current
    bands.append({"start": start, "end": previous})

    band_frame = pd.DataFrame(bands)
    # Extend each band by a month so a single thin month is still visible.
    band_frame["end"] = band_frame["end"] + pd.Timedelta(days=31)

    shading = (
        alt.Chart(band_frame)
        .mark_rect(color="#d62728", opacity=0.10)
        .encode(x=alt.X("start:T"), x2=alt.X2("end:T"))
    )
    caption = (
        alt.Chart(band_frame.head(1))
        .mark_text(
            align="left",
            baseline="top",
            dx=4,
            dy=4,
            fontSize=11,
            color="#d62728",
            text="thin data — low claim volume",
        )
        .encode(x=alt.X("start:T"))
    )
    return shading + caption


def control_query(sql: str, label: str = "The SQL control query behind this figure") -> None:
    """Print the control query a figure reconciles to, beside the figure.

    §7 asks that dashboard totals reconcile to SQL control queries. Putting the
    query on the page turns that from a claim into something a reader can run.
    """
    with st.expander(label, expanded=False):
        st.code(sql.strip(), language="sql")


def disclosure_block(
    title: str,
    body: str,
    expanded: bool = False,
    icon: str = ":material/info:",
) -> None:
    """A named disclosure, collapsed by default but never hidden.

    Collapsed rather than absent is a deliberate middle: the honesty text is long
    and putting all of it inline would push every figure below the fold, but a
    disclosure a reader cannot find is one that is not made. Every block is
    titled with its conclusion, so the heading alone carries the finding even
    unopened — "Model C is a negative result" says the thing before it is clicked.
    """
    with st.expander(title, expanded=expanded, icon=icon):
        st.markdown(body)


def required_disclosures(expanded: bool = False) -> None:
    """The two disclosures the human required on every user-facing surface.

    Vintage skew and the crosswalk collision / synthetic-ID keying rule, rendered
    from `dashboard/disclosures.py` so the dashboard, the API and the docs cannot
    drift into three wordings of the same fact.
    """
    summary_with_detail(
        disclosures.VINTAGE_SKEW_SUMMARY,
        disclosures.VINTAGE_SKEW,
        label="Full explanation — data vintage",
        icon=":material/schedule:",
    )
    summary_with_detail(
        disclosures.CROSSWALK_COLLISION_SUMMARY,
        f"{disclosures.CROSSWALK_COLLISION}\n\n{disclosures.CROSSWALK_ROW_COUNT_NOTE}",
        label="Full explanation — facility names and keying",
        icon=":material/link_off:",
    )


def data_source_caption() -> None:
    """What this process is reading, stamped with the commit it was built from."""
    from dashboard import data

    try:
        described = data.source_description()
    except data.DashboardDataError as error:
        st.warning(str(error))
        return

    if described.get("kind") == "bundle":
        commit = str(described.get("git_commit", "unknown"))[:12]
        dirty = (
            " (built from an UNCOMMITTED working tree)" if described.get("git_tree_dirty") else ""
        )
        st.caption(
            f"Reading the bundled DuckDB extract, built from commit `{commit}`{dirty} at "
            f"{described.get('built_at_utc', 'unknown')}. {disclosures.DEMO_EXTRACT_NOTE}"
        )
    else:
        st.caption(
            "Reading a LIVE PostgreSQL warehouse. The hosted demo does not — CLAUDE.md §2 "
            "locks it to the bundled extract, so figures here may differ from the deployed app "
            "if the warehouse has moved."
        )


# ---------------------------------------------------------------------------
# Frames on screen
# ---------------------------------------------------------------------------


def simulated_columns_caption(frame: pd.DataFrame) -> None:
    """Name the simulated columns of a table under the table.

    The `sim_` prefix is on every column header already (§3.2). This restates it
    as a sentence because a reader scanning a wide table reads the values, not the
    headers, and "seven of these fourteen columns describe events that never
    happened" is the thing they need.
    """
    from src.demo import spec

    simulated = spec.simulated_columns(list(frame.columns))
    if not simulated:
        st.caption("No `sim_` columns in this table.")
        return
    st.caption(
        f"**{len(simulated)} of {frame.shape[1]} columns are SIMULATED** "
        f"(`{'`, `'.join(simulated)}`) — generated by this project's simulation layer, "
        "not measured from anything."
    )


def prepare_dataframe(frame: pd.DataFrame, *, emitter: DashboardEmitter) -> pd.DataFrame:
    """The tabular boundary shared by every registered dashboard surface."""
    if not emitter.contains_simulated:
        raise ValueError(f"{emitter.module}: table emitter must declare simulated-content handling")
    return frame.copy(deep=False)


def dataframe(frame: pd.DataFrame, *, emitter: DashboardEmitter, **kwargs: Any) -> None:
    """A table plus its simulated-column caption. Always both."""
    displayed = prepare_dataframe(frame, emitter=emitter)
    st.dataframe(displayed, width="stretch", hide_index=True, **kwargs)
    simulated_columns_caption(displayed)


def money(value: float) -> str:
    return f"${value:,.0f}"


def percent(value: float, digits: int = 1) -> str:
    return f"{value * 100:.{digits}f}%"
