"""Shared UI, and the one component CLAUDE.md §6 makes non-optional.

**Every page renders `render_synthetic_data_banner()`. No page ships without it.**
That is §6 verbatim, and §3.5 is why it is absolute rather than a nicety: Medicare
fee-for-service has exactly ONE payer and our payer dimension is 100% simulated,
so a payer comparison without the banner is a comparison of five payers that do
not exist. `tests/contracts/test_dashboard_banner.py` (qa's) fails the build for
any page module that renders content without calling it.

The banner is a component and not a copied paragraph for the same reason
`dashboard/disclosures.py` exists: five pages retyping a disclosure is five
chances for one of them to be softer than the others, and the soft one is the one
a reader will quote back.

EVERY FIGURE ON EVERY PAGE CARRIES ITS PROVENANCE
--------------------------------------------------
`kpi_row` takes a classification per metric — SOURCE, DERIVED, REFERENCE or
SIMULATED (§3.1) — and prints it under the number. A dashboard is the surface most
likely to launder a simulated dollar into a real one, because a big styled metric
tile reads as a fact about the world. The class under it is what stops that, and
it is a required argument rather than an optional one so a tile cannot ship
without a decision having been made about it.

`control_query` prints the SQL a figure must reconcile to, right beside the
figure. §7 requires dashboard totals to reconcile to SQL control queries; showing
the query where the number is means a reader can check it instead of trusting it.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

import pandas as pd
import streamlit as st

from dashboard import disclosures

Classification = Literal["SOURCE", "DERIVED", "REFERENCE", "SIMULATED", "MIXED"]

#: What each provenance class means in one line, shown on hover. Wording is the
#: §3.1 wording, not a paraphrase.
_CLASS_HELP: dict[str, str] = {
    "SOURCE": "From the official CMS synthetic claim files, unmodified.",
    "DERIVED": "Computed from SOURCE fields by this project's warehouse.",
    "REFERENCE": "From an official published code or facility reference file.",
    "SIMULATED": "Generated by THIS PROJECT'S simulation layer. Not a real outcome.",
    "MIXED": "Combines SOURCE, DERIVED and SIMULATED inputs — see the note below.",
}

_CLASS_BADGE: dict[str, str] = {
    "SOURCE": ":blue-badge[SOURCE]",
    "DERIVED": ":violet-badge[DERIVED]",
    "REFERENCE": ":green-badge[REFERENCE]",
    "SIMULATED": ":red-badge[SIMULATED]",
    "MIXED": ":orange-badge[MIXED]",
}


# ---------------------------------------------------------------------------
# The banner. CLAUDE.md §6.
# ---------------------------------------------------------------------------


def _banner_markdown() -> str:
    """The banner text, from the single source of truth in `disclosures.py`."""
    return disclosures.SYNTHETIC_DATA_BANNER


def render_synthetic_data_banner(extra: str | None = None) -> None:
    """The §6 synthetic-data banner. Called at the top of every page.

    `extra` appends a page-specific note — the payer-dimension warning, the A/R
    shape note — INSIDE the same red block rather than beside it, so a reader
    cannot take the caveat and leave the banner behind.
    """
    body = _banner_markdown()
    if extra:
        body = f"{body}\n\n{extra}"
    st.error(body, icon=":material/warning:")


def render_page_header(title: str, subtitle: str) -> None:
    """Title and one-line framing. **Does NOT render the banner, on purpose.**

    An earlier version of this function called the banner itself, and every page
    got it — correctly, invisibly, and by a chain a reader of the page file could
    not see. qa's `tests/contracts/test_dashboard_banner.py` reported all five
    pages as unbannered and it was right to: what it checks is that the CALL is
    in the page, and a §6 obligation discharged two frames away is one a future
    author can drop by editing this function.

    So the banner call stays in the page, on its own line, under §6's own words.
    """
    st.title(title)
    st.caption(subtitle)


# ---------------------------------------------------------------------------
# KPI tiles with their provenance class attached
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Kpi:
    """One headline figure and the classification printed beneath it."""

    label: str
    value: str
    classification: Classification
    help: str = ""


def kpi_row(kpis: list[Kpi]) -> None:
    """A row of metric tiles, each stamped with its provenance class."""
    for column, kpi in zip(st.columns(len(kpis)), kpis, strict=True):
        with column:
            st.metric(
                kpi.label,
                kpi.value,
                help=f"{kpi.help}\n\n{kpi.classification}: {_CLASS_HELP[kpi.classification]}".strip(),
            )
            st.markdown(_CLASS_BADGE[kpi.classification])


def provenance_note(classification: Classification, text: str) -> None:
    """A classified note under a table or chart."""
    st.caption(f"{_CLASS_BADGE[classification]} {text}")


# ---------------------------------------------------------------------------
# Reconciliation, shown where the figure is
# ---------------------------------------------------------------------------


def control_query(sql: str, label: str = "The SQL control query behind this figure") -> None:
    """Print the control query a figure reconciles to, beside the figure.

    §7 asks that dashboard totals reconcile to SQL control queries. Putting the
    query on the page turns that from a claim into something a reader can run.
    """
    with st.expander(label, expanded=False):
        st.code(sql.strip(), language="sql")


def disclosure_block(
    title: str,
    body: str,
    expanded: bool = False,
    icon: str = ":material/info:",
) -> None:
    """A named disclosure, collapsed by default but never hidden.

    Collapsed rather than absent is a deliberate middle: the honesty text is long
    and putting all of it inline would push every figure below the fold, but a
    disclosure a reader cannot find is one that is not made. Every block is
    titled with its conclusion, so the heading alone carries the finding even
    unopened — "Model C is a negative result" says the thing before it is clicked.
    """
    with st.expander(title, expanded=expanded, icon=icon):
        st.markdown(body)


def required_disclosures(expanded: bool = False) -> None:
    """The two disclosures the human required on every user-facing surface.

    Vintage skew and the crosswalk collision / synthetic-ID keying rule, rendered
    from `dashboard/disclosures.py` so the dashboard, the API and the docs cannot
    drift into three wordings of the same fact.
    """
    disclosure_block(
        f"Data vintage — {disclosures.VINTAGE_SKEW_TITLE}",
        disclosures.VINTAGE_SKEW,
        expanded=expanded,
        icon=":material/schedule:",
    )
    disclosure_block(
        f"Facility names — {disclosures.CROSSWALK_COLLISION_TITLE}",
        f"{disclosures.CROSSWALK_COLLISION}\n\n{disclosures.CROSSWALK_ROW_COUNT_NOTE}",
        expanded=expanded,
        icon=":material/link_off:",
    )


def data_source_caption() -> None:
    """What this process is reading, stamped with the commit it was built from."""
    from dashboard import data

    try:
        described = data.source_description()
    except data.DashboardDataError as error:
        st.warning(str(error))
        return

    if described.get("kind") == "bundle":
        commit = str(described.get("git_commit", "unknown"))[:12]
        dirty = (
            " (built from an UNCOMMITTED working tree)" if described.get("git_tree_dirty") else ""
        )
        st.caption(
            f"Reading the bundled DuckDB extract, built from commit `{commit}`{dirty} at "
            f"{described.get('built_at_utc', 'unknown')}. {disclosures.DEMO_EXTRACT_NOTE}"
        )
    else:
        st.caption(
            "Reading a LIVE PostgreSQL warehouse. The hosted demo does not — CLAUDE.md §2 "
            "locks it to the bundled extract, so figures here may differ from the deployed app "
            "if the warehouse has moved."
        )


# ---------------------------------------------------------------------------
# Frames on screen
# ---------------------------------------------------------------------------


def simulated_columns_caption(frame: pd.DataFrame) -> None:
    """Name the simulated columns of a table under the table.

    The `sim_` prefix is on every column header already (§3.2). This restates it
    as a sentence because a reader scanning a wide table reads the values, not the
    headers, and "seven of these fourteen columns describe events that never
    happened" is the thing they need.
    """
    from src.demo import spec

    simulated = spec.simulated_columns(list(frame.columns))
    if not simulated:
        st.caption("No `sim_` columns in this table.")
        return
    st.caption(
        f"**{len(simulated)} of {frame.shape[1]} columns are SIMULATED** "
        f"(`{'`, `'.join(simulated)}`) — generated by this project's simulation layer, "
        "not measured from anything."
    )


def dataframe(frame: pd.DataFrame, **kwargs: Any) -> None:
    """A table plus its simulated-column caption. Always both."""
    st.dataframe(frame, width="stretch", hide_index=True, **kwargs)
    simulated_columns_caption(frame)


def money(value: float) -> str:
    return f"${value:,.0f}"


def percent(value: float, digits: int = 1) -> str:
    return f"{value * 100:.{digits}f}%"
