"""The canonical honesty text for every user-facing surface.

WHY THE STRINGS LIVE HERE AND NOT IN `src/`
-------------------------------------------
This module is the single source of truth for what the dashboard AND the API say
about provenance, and `src/api/` imports these constants rather than restating
them. The direction of that dependency is deliberate: the human's Phase 5
instruction was that two disclosures be visible **where a user sees the data**,
and the dashboard is that place. Keeping the sentences here, in the package a
reader of the app opens first, means the API cannot drift into a softer wording
than the screen — there is only one wording.

Every constant below is prose a person reads, not a label. `dashboard/tables.py`
holds the column-level provenance markers; this file holds the paragraphs.

WHAT MUST NOT BE SOFTENED, AND WHY EACH ONE IS HERE
---------------------------------------------------
* `SYNTHETIC_DATA_BANNER` — docs/project_rules.md §6 ("no page ships without it") and §3.5
  (the payer dimension is 100% simulated; Medicare FFS has ONE payer, so an
  unbannered payer comparison is a comparison of five payers that do not exist).
* `VINTAGE_SKEW` — the crosswalk reference files postdate the claims by about
  three years. `docs/provenance_register.md` has always recorded both vintages
  and has never once said they disagree. Recording two numbers in two places is
  what made this invisible; this paragraph states the mismatch as one thought.
* `CROSSWALK_COLLISION` — the numbers, not just the phrase "display-only".
  "Display-only" tells a reader not to trust the mapping. The ratio tells them a
  single real facility name stands for up to eight different synthetic
  providers, which is the fact that decides how every figure must be grouped.
* `MODEL_A_HONESTY`, `MODEL_C_HONESTY`, `DOLLARS_AT_RISK` — the Phase 4 results
  are two negative findings and one poorly-determined magnitude. A dashboard is
  the surface most likely to launder them into achievements, so the sentences
  that refuse to are pinned here rather than retyped per page.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# The banner. docs/project_rules.md §6: every page renders it. No exceptions.
# ---------------------------------------------------------------------------

SYNTHETIC_DATA_BANNER = (
    "**SIMULATED DATA — nothing on this page describes real payer behaviour.** "
    "The claims underneath are official CMS *synthetic* Medicare records (SOURCE). "
    "Every denial, appeal, payment, workflow event, operating cost and payer shown "
    "here is generated by this project's own simulation layer and is prefixed "
    "`sim_` wherever it appears. Medicare fee-for-service has exactly **one** "
    "payer; the five payer archetypes in this app are invented and are named after "
    "no real insurer. No real patient, provider, payer or adjudication data exists "
    "anywhere in this repository."
)

BANNER_SHORT = "SIMULATED — outcomes generated by this project's simulation layer, not real."

#: The §6 banner in one line, for pages after the first. Names where the full
#: text lives, so the short form points at the long one instead of replacing it.
BANNER_SHORT_PAGE = (
    "**⚠️ SIMULATED DATA** — every denial, appeal, payment and payer on this page "
    "is generated, not real. Full disclosure on the **Overview** page."
)

# What the API repeats in the metadata of any response carrying `sim_` fields.
API_SIMULATED_NOTICE = (
    "Every sim_-prefixed field in this response is SIMULATED by this project's "
    "adjudication layer (docs/project_rules.md §3). The underlying claims are official CMS "
    "synthetic Medicare records. No real patient, provider, payer or adjudication "
    "data is served by this API. The multi-payer dimension is 100% simulated — "
    "Medicare fee-for-service has one payer."
)

# ---------------------------------------------------------------------------
# Disclosure 1 — reference-file vintage skew
#
# Kept as ONE paragraph with no blank line in it, on purpose: the claims vintage
# and the reference vintage have to land on a reader as a single thought. Split
# across two paragraphs this becomes what the provenance register already was —
# two recorded facts that never meet.
# ---------------------------------------------------------------------------

VINTAGE_SKEW_TITLE = (
    "The facility and provider reference files are about three years newer than the claims"
)

#: One-sentence form. The full text below is unchanged and stays one click away.
VINTAGE_SKEW_SUMMARY = (
    "**Facility and provider reference data is about three years newer than the claims** "
    "(2026 files against 2023-04 claims), so any facility type, state or provider "
    "specialty shown here describes what was true *later*, not at the time of the claim. "
    "The diagnosis, procedure and DRG code sets are correctly matched to the claims."
)

VINTAGE_SKEW = (
    "The claims are vintage **2023-04**, and the code sets attached to them match: "
    "ICD-10-CM/PCS **FY2023**, HCPCS **2023** and MS-DRG v40 **FY2023** are all "
    "contemporaneous with the claims, so nothing in the diagnosis, procedure or "
    "DRG labelling carries a vintage problem. The two *crosswalk* reference files "
    "do not match. Hospital General Information is vintage **2026-04**, and the "
    "CMS Medicare Physician & Other Practitioners file is data year **2024** "
    "(released 2026-05) — roughly **three years newer** than the claims they are "
    "attached to. Hospitals open, close, merge and change type over three years, "
    "and physicians change specialty and state, so a facility type, a facility "
    "state or a provider specialty shown anywhere in this app is what the "
    "reference file recorded about three years AFTER the claim was filed, not "
    "necessarily what was true when it was filed. `config/sources.yaml` records "
    "every one of these vintages and is the authority on them; what it does not "
    "say, and what this paragraph exists to say, is that they disagree."
)

# ---------------------------------------------------------------------------
# Disclosure 2 — crosswalk collision and the keying rule
# ---------------------------------------------------------------------------

CROSSWALK_COLLISION_TITLE = (
    "Real facility names are display-only, and grouping on the NAME collides 15:1"
)

#: One-sentence form. The full text below is unchanged and stays one click away.
CROSSWALK_COLLISION_SUMMARY = (
    "**Real facility and provider names are for display only** — one real name can stand "
    "for up to 15 different synthetic providers, so nothing in this app is grouped or "
    "counted by name. Every facility and provider figure is keyed on the synthetic ID."
)

CROSSWALK_COLLISION = (
    "CMS synthetic claims carry synthetic provider and facility identifiers. They "
    "do not correspond to any real NPI or CCN and cannot be joined to one "
    "(docs/project_rules.md §3.4), so every real facility name in this app is "
    # "display-only" belongs in the PARAGRAPH, not only in the heading above it.
    # The heading is one line a reader can skim past, and it is also the one piece
    # of a Streamlit expander that no render test can currently read back.
    "**display-only**: it reaches this screen through a seeded "
    "random assignment, stratified by state and type, done purely so the app shows "
    "recognisable names instead of opaque codes. That crosswalk maps **4,876** "
    "synthetic billing providers onto only **2,857** real CCNs: 45.9% of those "
    "CCNs carry more than one synthetic provider, and the worst case is **8:1**. "
    "**Grouping on the facility NAME is worse still, and the name is what a "
    "dashboard is most likely to group on**, being the human-readable key: real "
    "CMS facilities share names across sites, so those 2,857 CCNs carry only "
    "**2,816 distinct display names**, 1,302 of which stand for more than one "
    "synthetic provider, and the worst case by name is **15:1** rather than 8:1. A "
    "real CCN and a real facility name are consequently not stable entity keys and "
    "are never used as one — every facility-level and provider-level figure in this "
    "app is grouped on the synthetic `prvdr_num`, never on `sim_facility_ccn` and "
    "never on `sim_facility_name`, because grouping on either would silently merge "
    "up to eight (by CCN) or fifteen (by name) distinct synthetic hospitals into "
    "one row and inflate its volume. The crosswalk is also "
    # Kept on ONE source line deliberately. qa's disclosure gate greps the Python
    # SOURCE of dashboard/ for this phrase, so a literal split across two adjacent
    # string fragments reads as absent even though the rendered paragraph says it.
    "**forbidden as a feature** in every model at every boundary, "
    "Model A and Model C alike: it carries no information about the claim, only a name."
)

#: 4,877 vs 4,876 is not a typo and is asked about every time. Said once, here.
CROSSWALK_ROW_COUNT_NOTE = (
    "`vw_clean_claim_performance` has **4,877** rows while the crosswalk has "
    "**4,876** entries. Both figures are right: one synthetic billing provider has "
    "no crosswalk row and therefore no display name, and the view keeps it because "
    "dropping a provider from a provider-level view to make two numbers agree "
    "would be the wrong repair."
)

# ---------------------------------------------------------------------------
# Model results — the two negative findings, stated as findings
# ---------------------------------------------------------------------------

#: One-sentence form. The full text below is unchanged and stays one click away.
MODEL_A_SUMMARY = (
    "**The best model is a simple logistic regression.** It beats a naive baseline, but a "
    "more complex model (XGBoost) does not improve on it — which is the expected result "
    "given how this data was generated, not a disappointment."
)

MODEL_A_HONESTY = (
    "**The advanced model does not beat the baseline, and that is the reported "
    "result.** Model A's champion is a regularized logistic regression at ROC-AUC "
    "0.6254 / PR-AUC 0.2210 on the forward test fold. XGBoost − logistic is "
    "+0.0003 [−0.0173, +0.0183]: an interval an order of magnitude wider than the "
    "point estimate, so it is reported as *no difference*, not as a tie broken in "
    "anyone's favour. Against a baseline that is not a strawman the model does "
    "earn its place — logistic − payer rule is +0.0333 [+0.0066, +0.0571] ROC and "
    "+0.0695 [+0.0444, +0.0998] PR, both excluding zero. 0.625 is also close to "
    "where it should be: scoring with the generator's own latent probability "
    "reaches only ~0.68, because roughly **a third of the simulated denials carry "
    "no mechanism signal at all** and exist only as deliberate label noise. A "
    "score above 0.75 fails the training run as a suspected bug."
)

#: One-sentence form. The full text below is unchanged and one click away.
MODEL_A_EXPLANATION_LIMIT_SUMMARY = "**About a third of these denials have no explanation to find.** They were generated as deliberate noise, so SHAP will still produce a chart for them — but it explains the model, not the claim."

MODEL_A_EXPLANATION_LIMIT = (
    "**Expect no explanation for about a third of these denials.** ~33% of "
    "simulated denials are pure label noise by construction, with no mechanism "
    "behind them. SHAP will still decompose them, because SHAP always does — it "
    "explains the model, not the world. A waterfall is not a claim-level causal "
    "account, and an explanation of an unexplainable denial would be a "
    "fabrication."
)

#: One-sentence form. The full text below is unchanged and stays one click away.
MODEL_C_SUMMARY = (
    "**The ML ranking for appeal recovery does not outperform simply working the largest "
    "denials first** — reported here as a negative result rather than hidden. The score "
    "still decides *which* claims are worth working at all, just not their order."
)

MODEL_C_HONESTY = (
    "**Model C is a negative result and is presented as one.** The champion "
    "(XGBoost, ROC-AUC 0.5611 on 193 test rows) does not beat a rule that needs no "
    "model: xgboost − denial-category rule is −0.0356 [−0.1325, +0.0597], an "
    "interval spanning zero. No slice beats chance — every payer, service-line and "
    "denial-category interval covers 0.5. At 10% capacity, simply working the "
    "**largest denial first captures 65.7%** of recoverable dollars, against 61.0% "
    "for the Expected Net Recovery score and 59.8% for the tiered queue that "
    "ships. **The probability does not earn its place in the ordering.** Expected "
    "Net Recovery ships for the *cutoff* — which claims clear the cost of working "
    "them — and for the policy *tiering*, not because it ranks better than sorting "
    "by dollar amount. It does not."
)

#: One-sentence form. The full text below is unchanged and one click away.
MODEL_C_NO_SHAP_SUMMARY = "**No SHAP charts for Model C, on purpose** — the model is not distinguishable from a simple lookup table, so per-claim explanations would imply a precision the numbers do not support. Analysts get the tier and recommended action instead."

MODEL_C_NO_SHAP = (
    "**No SHAP is published for Model C, deliberately.** A model that cannot be "
    "separated from a lookup table has nothing stable to attribute, and per-claim "
    "waterfalls over it would manufacture the impression the numbers refuse to "
    "support. What an analyst gets instead is the queue's **tier** and its "
    "**recommended action** — rule-based, auditable, and true by construction "
    "rather than estimated."
)

#: One-sentence form. The full text below is unchanged and one click away.
MODEL_C_SELECTION_LIMIT_SUMMARY = "**This model learned only from denials somebody chose to appeal, but scores all of them.** Timely-filing denials were never appealed, so it has no training support there and still emits a score. Measured, not assumed away."

MODEL_C_SELECTION_LIMIT = (
    "**Model C is fitted on the 967 denials somebody chose to appeal and applied "
    "to all 2,663.** Those are not the same claims: MEDICAL_NECESSITY denials were "
    "appealed 47.6% of the time, DUPLICATE_CLAIM 9.8%, and TIMELY_FILING **0.0%** "
    "— so for timely-filing denials the model has no training support at all and "
    "still emits a score. This is selection on the outcome's own decision and it "
    "cannot be fixed from this data. It is measured rather than assumed away."
)

#: One-sentence form. The full text below is unchanged and one click away.
DOLLARS_AT_RISK_SUMMARY = "**The model does surface more denied dollars than ranking at random, but by how much is not pinned down** — the range is wide (+4.2 to +51.7 points), so no single figure from this should be quoted."

DOLLARS_AT_RISK = (
    "**Dollars at risk is measurable here but not precise, and no single number "
    "from it should be quoted.** Denied dollars in the test fold are heavily "
    "concentrated — the ten largest denied claims hold **50.9%** of the money at "
    "risk — so two point estimates with overlapping intervals cannot settle "
    "whether one ranking beats another. Read as a paired bootstrap on the "
    "difference, the champion captures about **18 percentage points** more denied "
    "dollars than arbitrary ranking, and the interval runs from +4.2 to +51.7 "
    "points. The sign is established; the magnitude is not. A +4.2 point floor and "
    "a +51.7 point ceiling describe different businesses."
)

#: One-sentence form. The full text below is unchanged and one click away.
OPERATING_POINT_SUMMARY = "**Working the top 10% of the queue catches about 1 in 5 denials, at 2.2× better than chance.** Roughly three in four flagged claims would not have been denied, so this flags work for a human — it is not a payment or clinical decision."

OPERATING_POINT = (
    "**The capacity-constrained operating point is the primary one**, because a "
    "work queue is ranked against finite analyst hours rather than thresholded "
    "against a guess. Reviewing the top 10% by score flags 9.6% of claims at 20.9% "
    "recall and **26.3% precision — 2.2× the base rate**. Roughly three in four "
    "flagged claims would not have been denied, so this flags claims for a human; "
    "it is not a payment decision, not a clinical determination, and not a reason "
    "to hold a claim without someone looking at it."
)

NOT_A_FRAUD_SIGNAL = (
    "A queued claim is a **work item**, and a low clean-claim rate is a **process "
    "review flag** for that synthetic provider. Neither is an accusation of fraud, "
    "and nothing in this app should be read as one."
)

# ---------------------------------------------------------------------------
# Per-page provenance footnotes, keyed by the page that renders them.
# ---------------------------------------------------------------------------

PAYER_DIMENSION_NOTE = (
    "**The payer dimension on this page is 100% invented (docs/project_rules.md §3.5).** "
    "Medicare fee-for-service has exactly one payer. The five archetypes below are "
    "simulated, are modelled on and named after no real insurer, and no row here "
    "describes real Medicare, Medicare Advantage, commercial or Medicaid "
    "adjudication behaviour."
)

#: One-sentence form. The full text below is unchanged and one click away.
AR_AGING_NOTE_SUMMARY = "**All open A/R sits in the oldest bucket — that is expected here, not a bug.** In this simulated book every unpaid claim is a full denial and the denials stop in 2023, so the younger buckets are genuinely empty and are still drawn."

AR_AGING_NOTE = (
    "**Expected shape, not a bug.** In this simulated book every unpaid claim is a "
    "never-paid full denial and the denials stop in 2023, so relative to the "
    "2024-07 snapshot all open A/R falls in the 120+ day bucket (minimum ~481 "
    "days). The 0–30 through 91–120 buckets legitimately show zero and are still "
    "drawn, so the emptiness is visible rather than hidden."
)

PROVIDER_VOLUME_NOTE = (
    "**Volumes are shown beside every rate, always.** The median provider in this "
    "warehouse has two claims and never builds a usable history, so a rate on a "
    "thin denominator is noise wearing a percentage sign. Do not rank "
    "single-claim providers."
)

DEMO_EXTRACT_NOTE = (
    "This app is reading a bundled DuckDB extract of the curated warehouse views, "
    "not a live database (a locked project decision — the hosted demo ships its "
    "own data). The extract is built by `make demo-extract` from PostgreSQL and "
    "carries the git commit and build timestamp it was made at, shown on the Model "
    "& data quality page."
)

__all__ = [
    "AR_AGING_NOTE",
    "API_SIMULATED_NOTICE",
    "BANNER_SHORT",
    "CROSSWALK_COLLISION",
    "CROSSWALK_COLLISION_TITLE",
    "CROSSWALK_ROW_COUNT_NOTE",
    "DEMO_EXTRACT_NOTE",
    "DOLLARS_AT_RISK",
    "MODEL_A_EXPLANATION_LIMIT",
    "MODEL_A_HONESTY",
    "MODEL_C_HONESTY",
    "MODEL_C_NO_SHAP",
    "MODEL_C_SELECTION_LIMIT",
    "NOT_A_FRAUD_SIGNAL",
    "OPERATING_POINT",
    "PAYER_DIMENSION_NOTE",
    "PROVIDER_VOLUME_NOTE",
    "SYNTHETIC_DATA_BANNER",
    "VINTAGE_SKEW",
    "VINTAGE_SKEW_TITLE",
]
