-- ============================================================================
-- 50_sim_adjudication.sql — the SIMULATED adjudication layer (CLAUDE.md §3)
--
-- Grain:        sim_payer                     : one simulated payer archetype
--               sim_service_line              : one simulated service-line bucket
--               sim_authorization_eligibility : one claim (pre-submission facts)
--               sim_documentation_coding      : one claim (pre-submission facts)
--               sim_claim_adjudication        : one claim (outcome + money + dates)
--               sim_appeals                   : one (claim, appeal level)
--               sim_workflow_events           : one (claim, event occurrence)
--               sim_operating_costs           : one claim
--
-- Sources:      GENERATED by src/simulation/ from config/simulation.yaml.
--               Conditioned on SOURCE claim attributes (charges, DRG, dates,
--               diagnosis count) but no SOURCE value is copied into a sim_
--               column — billed charges stay in rcm.fact_inpatient_claim and are
--               reached by joining on claim_sk.
--
-- Provenance:   SIMULATED, every table and every column (§3.1, §3.2). The CMS
--               synthetic claims contain NO denials, NO submission/adjudication
--               dates, NO appeals and NO workflow events; all of that is
--               invented here. Nothing in these tables describes real Medicare,
--               Medicare Advantage, commercial or Medicaid adjudication
--               behaviour. Calibration anchors: docs/assumptions.md.
--
-- Owner:        simulation-engineer (§5). Loaded by src/simulation/load_sim.py
--               (`make simulate-warehouse`), NOT by the Phase 1 loader.
--
-- ORDERING:     these tables carry foreign keys to rcm.fact_inpatient_claim.
--               `make warehouse` drops that table with CASCADE, which silently
--               drops those constraints. Correct order is always:
--                   make warehouse  ->  make simulate  ->  make simulate-warehouse
--               The loader refuses to run if the fact table is absent.
--
-- Notes:        sim_ prefix on every identifier except claim_sk / clm_id, which
--               are the warehouse's DERIVED surrogate and SOURCE degenerate key
--               — renaming those would misrepresent their provenance.
--               Idempotent drop/recreate. PostgreSQL 16.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- sim_payer — the simulated multi-payer dimension (CLAUDE.md §3.5).
-- Medicare FFS has ONE payer; every payer below is an invented ARCHETYPE, not
-- modelled on or named after any real insurer.
-- ---------------------------------------------------------------------------
drop table if exists rcm.sim_payer cascade;
create table rcm.sim_payer (
    sim_payer_id           text primary key,
    sim_payer_name         text not null,
    sim_payer_mix_share    numeric(6, 4) not null,
    sim_timely_filing_days integer not null,
    sim_provenance         text not null default 'SIMULATED',
    sim_config_version     text not null,
    sim_seed               bigint not null,
    constraint ck_sim_payer_mix check (sim_payer_mix_share between 0 and 1),
    constraint ck_sim_payer_filing check (sim_timely_filing_days > 0)
);
-- NOTE: this file must contain no literal percent-sign character anywhere,
-- including in comments. psycopg2 reads one as a parameter placeholder and the
-- entire DDL script then fails to execute. Write "percent" or "share" instead.
comment on table rcm.sim_payer is
  'SIMULATED: invented payer archetypes. Medicare FFS has one payer; this '
  'multi-payer dimension is entirely simulated (CLAUDE.md §3.5).';

-- ---------------------------------------------------------------------------
-- sim_service_line — coarse MS-DRG range buckets. The boundaries are a design
-- choice OF THIS SIMULATION, not an official CMS MS-DRG/MDC taxonomy, which is
-- why the column is SIMULATED even though its input (drg_cd) is SOURCE.
-- ---------------------------------------------------------------------------
drop table if exists rcm.sim_service_line cascade;
create table rcm.sim_service_line (
    sim_service_line_id   text primary key,
    sim_service_line_name text not null,
    sim_drg_range_lo      integer,          -- null on the UNKNOWN (no-DRG) member
    sim_drg_range_hi      integer,
    sim_provenance        text not null default 'SIMULATED',
    sim_config_version    text not null,
    sim_seed              bigint not null,
    constraint ck_sim_sl_range check (
        sim_drg_range_lo is null or sim_drg_range_hi is null
        or sim_drg_range_lo <= sim_drg_range_hi
    )
);
comment on table rcm.sim_service_line is
  'SIMULATED: service-line buckets defined by this project as MS-DRG numeric '
  'ranges. NOT an official CMS grouping.';

-- ---------------------------------------------------------------------------
-- sim_authorization_eligibility — PRE-SUBMISSION facts. Everything here is
-- knowable before a claim goes out the door, so these ARE legitimate features
-- for the Model A denial-risk problem (CLAUDE.md §4).
-- ---------------------------------------------------------------------------
drop table if exists rcm.sim_authorization_eligibility cascade;
create table rcm.sim_authorization_eligibility (
    claim_sk                    bigint primary key
        references rcm.fact_inpatient_claim (claim_sk),
    clm_id                      text not null,
    sim_payer_id                text not null references rcm.sim_payer (sim_payer_id),
    sim_auth_required           boolean not null,
    sim_auth_obtained           boolean not null,
    sim_auth_missing            boolean not null,
    sim_auth_obtained_late      boolean not null,
    sim_auth_reference_id       text,           -- invented id, not a real auth number
    sim_auth_request_date       date,
    sim_auth_decision_date      date,
    sim_eligibility_checked     boolean not null,
    sim_eligibility_failed      boolean not null,
    sim_eligibility_check_date  date,
    sim_secondary_payer_present boolean not null,
    sim_provenance              text not null default 'SIMULATED',
    sim_config_version          text not null,
    sim_seed                    bigint not null,
    -- An authorization cannot be both obtained and missing, and neither can be
    -- true when none was required.
    constraint ck_sim_auth_exclusive check (not (sim_auth_obtained and sim_auth_missing)),
    constraint ck_sim_auth_requires_required check (
        sim_auth_required or (not sim_auth_obtained and not sim_auth_missing)
    ),
    constraint ck_sim_elig_requires_check check (sim_eligibility_checked or not sim_eligibility_failed)
);
create index ix_sim_auth_payer on rcm.sim_authorization_eligibility (sim_payer_id);
comment on table rcm.sim_authorization_eligibility is
  'SIMULATED pre-submission authorization/eligibility facts. Invented; the CMS '
  'synthetic claims contain no authorization or eligibility data.';

-- ---------------------------------------------------------------------------
-- sim_documentation_coding — PRE-SUBMISSION documentation/coding facts.
-- Also legitimate Model A features.
-- ---------------------------------------------------------------------------
drop table if exists rcm.sim_documentation_coding cascade;
create table rcm.sim_documentation_coding (
    claim_sk                       bigint primary key
        references rcm.fact_inpatient_claim (claim_sk),
    clm_id                         text not null,
    sim_documentation_complete     boolean not null,
    sim_documentation_score        numeric(6, 4) not null,
    sim_coder_query_outstanding    boolean not null,
    sim_coding_specificity_deficit boolean not null,
    sim_coding_complexity_score    numeric(6, 4) not null,
    sim_duplicate_submission_flag  boolean not null,
    sim_provenance                 text not null default 'SIMULATED',
    sim_config_version             text not null,
    sim_seed                       bigint not null,
    constraint ck_sim_doc_score  check (sim_documentation_score between 0 and 1),
    constraint ck_sim_cplx_score check (sim_coding_complexity_score between 0 and 1)
);
comment on table rcm.sim_documentation_coding is
  'SIMULATED pre-submission documentation and coding quality facts. Invented.';

-- ---------------------------------------------------------------------------
-- sim_claim_adjudication — the hub. One row per claim: generated timeline,
-- generated money, generated denial outcome.
--
-- LEAKAGE WARNING (CLAUDE.md §4): almost every column here is POST-SUBMISSION
-- and must be on the Model A forbidden list — the outcome, all money, all
-- adjudication/payment dates. sim_latent_p and sim_provider_quality_latent are
-- generator internals stored for VALIDATION ONLY and must never be features.
-- The authoritative list is docs/simulated_forbidden_columns.md.
-- The exceptions (legitimately pre-submission): sim_payer_id,
-- sim_service_line_id, sim_coded_date, sim_submission_date,
-- sim_filing_limit_days, sim_days_service_to_submission, sim_late_filing_flag.
-- ---------------------------------------------------------------------------
drop table if exists rcm.sim_claim_adjudication cascade;
create table rcm.sim_claim_adjudication (
    claim_sk                          bigint primary key
        references rcm.fact_inpatient_claim (claim_sk),
    clm_id                            text not null unique,
    sim_payer_id                      text not null references rcm.sim_payer (sim_payer_id),
    sim_service_line_id               text not null
        references rcm.sim_service_line (sim_service_line_id),
    -- ---- timeline (all generated; the source has service dates only) ----
    sim_coded_date                    date not null,
    sim_submission_date               date not null,
    sim_ack_date                      date not null,
    sim_adjudication_date             date not null,
    sim_denial_review_date            date,          -- denied claims only
    sim_payment_date                  date,          -- claims with a payment only
    sim_filing_limit_days             integer not null,
    sim_days_service_to_submission    integer not null,
    sim_days_to_adjudication          integer not null,
    sim_days_to_payment               integer,
    sim_late_filing_flag              boolean not null,
    -- ---- money (allowed/paid/adjustment; billed stays in the SOURCE fact) ----
    sim_allowed_amount                numeric(14, 2) not null,
    sim_paid_amount                   numeric(14, 2) not null,
    sim_patient_responsibility_amount numeric(14, 2) not null,
    sim_contractual_adjustment_amount numeric(14, 2) not null,
    sim_denied_amount                 numeric(14, 2) not null,
    -- ---- outcome ----
    sim_denial_flag                   boolean not null,
    sim_denial_type                   text not null,  -- NONE | FULL | PARTIAL
    sim_denial_category               text,           -- catalog id; null iff not denied
    sim_denial_carc_group             text,           -- CARC code as a LABEL only (§3.7)
    sim_denial_driver_mechanism       text,           -- strongest contributing mechanism
    -- ---- generator internals: VALIDATION ONLY, never a model feature ----
    sim_latent_p                      numeric(10, 6) not null,
    sim_label_noise_applied           boolean not null,
    sim_provider_quality_latent       numeric(10, 6) not null,
    sim_provenance                    text not null default 'SIMULATED',
    sim_config_version                text not null,
    sim_seed                          bigint not null,
    -- Money invariants. paid <= allowed is enforced here; allowed <= billed
    -- needs the SOURCE fact table and is checked by the validation suite.
    constraint ck_sim_adj_nonneg check (
        sim_allowed_amount >= 0 and sim_paid_amount >= 0
        and sim_patient_responsibility_amount >= 0
        and sim_contractual_adjustment_amount >= 0 and sim_denied_amount >= 0
    ),
    constraint ck_sim_adj_paid_le_allowed check (sim_paid_amount <= sim_allowed_amount),
    constraint ck_sim_adj_latent_p check (sim_latent_p > 0 and sim_latent_p < 1),
    constraint ck_sim_adj_denial_type check (sim_denial_type in ('NONE', 'FULL', 'PARTIAL')),
    -- A denial has a category and a type; a paid claim has neither.
    constraint ck_sim_adj_category_iff_denied check (
        (sim_denial_flag and sim_denial_category is not null and sim_denial_type <> 'NONE')
        or (not sim_denial_flag and sim_denial_category is null and sim_denial_type = 'NONE')
    ),
    constraint ck_sim_adj_date_order check (
        sim_coded_date <= sim_submission_date
        and sim_submission_date <= sim_ack_date
        and sim_ack_date <= sim_adjudication_date
        and (sim_payment_date is null or sim_payment_date >= sim_adjudication_date)
        and (sim_denial_review_date is null or sim_denial_review_date >= sim_adjudication_date)
    )
);
create index ix_sim_adj_payer     on rcm.sim_claim_adjudication (sim_payer_id);
create index ix_sim_adj_sl        on rcm.sim_claim_adjudication (sim_service_line_id);
create index ix_sim_adj_denial    on rcm.sim_claim_adjudication (sim_denial_flag);
create index ix_sim_adj_category  on rcm.sim_claim_adjudication (sim_denial_category);
create index ix_sim_adj_submitted on rcm.sim_claim_adjudication (sim_submission_date);
comment on table rcm.sim_claim_adjudication is
  'SIMULATED adjudication outcomes, money and timeline. The CMS synthetic claims '
  'contain none of this. Does NOT represent real payer behaviour (CLAUDE.md §3, '
  'docs/assumptions.md). Most columns are post-submission — see '
  'docs/simulated_forbidden_columns.md before using any of it as a feature.';

-- ---------------------------------------------------------------------------
-- sim_appeals — one row per (claim, appeal level). Denied claims only.
-- Entirely post-submission: forbidden for Model A, and the label source for
-- Model C (appeal success).
-- ---------------------------------------------------------------------------
drop table if exists rcm.sim_appeals cascade;
create table rcm.sim_appeals (
    sim_appeal_sk               bigint primary key,
    claim_sk                    bigint not null
        references rcm.sim_claim_adjudication (claim_sk),
    clm_id                      text not null,
    sim_appeal_level            smallint not null,
    sim_appeal_filed_date       date not null,
    sim_appeal_decision_date    date not null,
    sim_appeal_outcome          text not null,   -- OVERTURNED | UPHELD
    sim_appeal_disputed_amount  numeric(14, 2) not null,
    sim_appeal_recovered_amount numeric(14, 2) not null,
    sim_appeal_latent_p         numeric(10, 6) not null,  -- VALIDATION ONLY
    sim_provenance              text not null default 'SIMULATED',
    sim_config_version          text not null,
    sim_seed                    bigint not null,
    constraint uq_sim_appeal_grain unique (claim_sk, sim_appeal_level),
    constraint ck_sim_appeal_level   check (sim_appeal_level in (1, 2)),
    constraint ck_sim_appeal_outcome check (sim_appeal_outcome in ('OVERTURNED', 'UPHELD')),
    constraint ck_sim_appeal_amounts check (
        sim_appeal_disputed_amount >= 0 and sim_appeal_recovered_amount >= 0
        and sim_appeal_recovered_amount <= sim_appeal_disputed_amount
    ),
    -- Nothing is recovered on an appeal that was upheld.
    constraint ck_sim_appeal_recovery_iff_overturned check (
        sim_appeal_outcome = 'OVERTURNED' or sim_appeal_recovered_amount = 0
    ),
    constraint ck_sim_appeal_dates check (sim_appeal_filed_date <= sim_appeal_decision_date)
);
create index ix_sim_appeal_claim   on rcm.sim_appeals (claim_sk);
create index ix_sim_appeal_outcome on rcm.sim_appeals (sim_appeal_outcome);
comment on table rcm.sim_appeals is
  'SIMULATED appeals. Invented; the CMS synthetic claims contain no appeals.';

-- ---------------------------------------------------------------------------
-- sim_workflow_events — the event log for process mining. One row per event
-- occurrence, sequenced within a claim by generated timestamp.
-- Post-submission events are forbidden Model A features (CLAUDE.md §4).
-- ---------------------------------------------------------------------------
drop table if exists rcm.sim_workflow_events cascade;
create table rcm.sim_workflow_events (
    sim_event_sk       bigint primary key,
    claim_sk           bigint not null references rcm.fact_inpatient_claim (claim_sk),
    clm_id             text not null,
    sim_event_seq      integer not null,
    sim_event_type     text not null,
    sim_activity       text not null,
    sim_event_date     date not null,
    sim_event_ts       timestamp not null,
    sim_actor_role     text not null,
    sim_appeal_level   smallint not null,   -- 0 when not an appeal event
    sim_touch_minutes  numeric(10, 2) not null,
    sim_provenance     text not null default 'SIMULATED',
    sim_config_version text not null,
    sim_seed           bigint not null,
    constraint uq_sim_event_grain unique (claim_sk, sim_event_seq),
    constraint ck_sim_event_seq     check (sim_event_seq >= 1),
    constraint ck_sim_event_minutes check (sim_touch_minutes >= 0),
    constraint ck_sim_event_level   check (sim_appeal_level between 0 and 2)
);
create index ix_sim_event_claim on rcm.sim_workflow_events (claim_sk);
create index ix_sim_event_type  on rcm.sim_workflow_events (sim_event_type);
create index ix_sim_event_ts    on rcm.sim_workflow_events (sim_event_ts);
comment on table rcm.sim_workflow_events is
  'SIMULATED workflow event log for process mining. Invented; the CMS synthetic '
  'claims contain no workflow events.';

-- ---------------------------------------------------------------------------
-- sim_operating_costs — cost to collect, built bottom-up from the touch minutes
-- in sim_workflow_events so the two tables reconcile by construction.
-- ---------------------------------------------------------------------------
drop table if exists rcm.sim_operating_costs cascade;
create table rcm.sim_operating_costs (
    claim_sk                 bigint primary key
        references rcm.sim_claim_adjudication (claim_sk),
    clm_id                   text not null,
    sim_touch_minutes_total  numeric(12, 2) not null,
    sim_coding_cost          numeric(12, 2) not null,
    sim_submission_cost      numeric(12, 2) not null,
    sim_payment_posting_cost numeric(12, 2) not null,
    sim_denial_rework_cost   numeric(12, 2) not null,
    sim_appeal_cost          numeric(12, 2) not null,
    sim_total_cost_to_collect numeric(12, 2) not null,
    sim_provenance           text not null default 'SIMULATED',
    sim_config_version       text not null,
    sim_seed                 bigint not null,
    constraint ck_sim_cost_nonneg check (
        sim_touch_minutes_total >= 0 and sim_coding_cost >= 0 and sim_submission_cost >= 0
        and sim_payment_posting_cost >= 0 and sim_denial_rework_cost >= 0
        and sim_appeal_cost >= 0 and sim_total_cost_to_collect >= 0
    )
);
comment on table rcm.sim_operating_costs is
  'SIMULATED cost to collect, derived from simulated touch minutes. Invented.';
